# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcTffSZ5a6EmAFgnCtY8hhxJQcXe-_4c
"""

import numpy as np
import pandas as pd
from datetime import datetime as dt



CGM = pd.read_csv('/content/CGMData.csv')
Insulin = pd.read_csv('/content/InsulinData.csv') 

CGM_D = pd.DataFrame(CGM, columns=['Date','Time','Sensor Glucose (mg/dL)'])

Insulin_D = pd.DataFrame(Insulin, columns=['Date','Time','Alarm'])



CGM_D['Date']=pd.to_datetime(CGM_D['Date']).dt.date

Insulin_D['Date']=pd.to_datetime(Insulin_D['Date']).dt.date



CGM_D['Time']=pd.to_datetime(CGM_D['Time']).dt.time

Insulin_D['Time']=pd.to_datetime(Insulin_D['Time']).dt.time



CGM_D['Sensor Glucose (mg/dL)'] = pd.to_numeric(CGM_D['Sensor Glucose (mg/dL)'])



Manual_Automode=Insulin_D.loc[Insulin_D['Alarm']=='AUTO MODE ACTIVE PLGM OFF']



startdate_auto=Manual_Automode.iloc[1,0] 

starttime_auto=Manual_Automode.iloc[1,1] 




cgm_Manual=CGM_D.loc[(CGM_D['Date']<startdate_auto) | ((CGM_D['Date']==startdate_auto) & (CGM_D['Time']<starttime_auto) )]

cgm_Manual=cgm_Manual.dropna() 



cgm_Auto=CGM_D.loc[(CGM_D['Date']>startdate_auto) | ((CGM_D['Date']==startdate_auto) & (CGM_D['Time']>=starttime_auto) )]

cgm_Auto=cgm_Auto.dropna()




def calculate(subset_data, typeVal = -1, lessthan = 1, greaterthan = 1):
    if (typeVal == 1):
        value_c=subset_data.loc[subset_data.iloc[:,2]<lessthan]
    if (typeVal == 2):
        value_c=subset_data.loc[subset_data.iloc[:,2]>greaterthan]
    if (typeVal == 3):
        value_c=subset_data.loc[(subset_data.iloc[:,2]>=greaterthan) & (subset_data.iloc[:,2]<=lessthan)]
    
    cgm_date=subset_data.groupby('Date')
    cal=value_c.groupby('Date').size().reset_index()
    cal=cal.set_index('Date')
    cal.columns=['Value']
    z=cal['Value']
    p=z/288
    p=p.to_frame()
    p['Value']=p['Value']*100
    avg_val=(p['Value'].sum())/len(cgm_date)
    return avg_val
    
Manual_fullDay180 = calculate(cgm_Manual, 2, 0, 180)

Manual_fullDay250 = calculate(cgm_Manual, 2, 0, 250)

Manual_fullDay70_180 = calculate(cgm_Manual, 3, 180, 70)

Manual_fullDay70_150 = calculate(cgm_Manual, 3, 150, 70)

Manual_fullDay70 = calculate(cgm_Manual, 1, 70, 0)

Manual_fullDay54 = calculate(cgm_Manual, 1, 54, 0)


Auto_fullDay180 = calculate(cgm_Auto, 2, 0, 180)

Auto_fullDay250 = calculate(cgm_Auto, 2, 0, 250)

Auto_fullDay70_180 = calculate(cgm_Auto, 3, 180, 70)

Auto_fullDay70_150= calculate(cgm_Auto, 3, 150, 70)

Auto_fullDay70 = calculate(cgm_Auto, 1, 70, 0)

Auto_fullDay54 = calculate(cgm_Auto, 1, 54, 0)


start=dt.strptime('00:00:00','%H:%M:%S').time()

end=dt.strptime('06:00:00','%H:%M:%S').time()

cgm_Manual_overnight=cgm_Manual.loc[(cgm_Manual['Time']>=start) & (cgm_Manual['Time']<end)]

cgm_Auto_overnight=cgm_Auto.loc[(cgm_Auto['Time']>=start) & (cgm_Auto['Time']<end)]



Manual_overnight_180 = calculate(cgm_Manual_overnight, 2, 0, 180)

Manual_overnight_250 = calculate(cgm_Manual_overnight, 2, 0, 250)

Manual_overnight_70_180 = calculate(cgm_Manual_overnight, 3, 180, 70)

Manual_overnight_70_150 = calculate(cgm_Manual_overnight, 3, 150, 70)

Manual_overnight_70 = calculate(cgm_Manual_overnight, 1, 70, 0)

Manual_overnight_54 = calculate(cgm_Manual_overnight, 1, 54, 0)


Auto_overnight_180 = calculate(cgm_Auto_overnight, 2, 0, 180)

Auto_overnight_250 = calculate(cgm_Auto_overnight, 2, 0, 250)

Auto_overnight_70_180 = calculate(cgm_Auto_overnight, 3, 180, 70)

Auto_overnight_70_150= calculate(cgm_Auto_overnight, 3, 150, 70)

Auto_overnight_70 = calculate(cgm_Auto_overnight, 1, 70, 0)

Auto_overnight_54 = calculate(cgm_Auto_overnight, 1, 54, 0)


start=dt.strptime('06:00:00','%H:%M:%S').time()

end=dt.strptime('23:59:00','%H:%M:%S').time()

cgm_Manual_daytime=cgm_Manual.loc[(cgm_Manual['Time']>=start) & (cgm_Manual['Time']<=end)]

cgm_Auto_daytime=cgm_Auto.loc[(cgm_Auto['Time']>=start) & (cgm_Auto['Time']<end)]



Manual_daytime_180 = calculate(cgm_Manual_daytime, 2, 0, 180)

Manual_daytime_250 = calculate(cgm_Manual_daytime, 2, 0, 250)

Manual_daytime_70_180 = calculate(cgm_Manual_daytime, 3, 180, 70)

Manual_daytime_70_150 = calculate(cgm_Manual_daytime, 3, 150, 70)

Manual_daytime_70 = calculate(cgm_Manual_daytime, 1, 70, 0)

Manual_daytime_54 = calculate(cgm_Manual_daytime, 1, 54, 0)


Auto_daytime180 = calculate(cgm_Auto_daytime, 2, 0, 180)

Auto_daytime250 = calculate(cgm_Auto_daytime, 2, 0, 250)

Auto_daytime70_180 = calculate(cgm_Auto_daytime, 3, 180, 70)

Auto_daytime70_150 = calculate(cgm_Auto_daytime, 3, 150, 70)

Auto_daytime70 = calculate(cgm_Auto_daytime, 1, 70, 0)

Auto_daytime54 = calculate(cgm_Auto_daytime, 1, 54, 0)



data = [[Manual_overnight_180,Manual_overnight_250,Manual_overnight_70_180,Manual_overnight_70_150,Manual_overnight_70,Manual_overnight_54,Manual_daytime_180,Manual_daytime_250,Manual_daytime_70_180,Manual_daytime_70_150,Manual_daytime_70,Manual_daytime_54,Manual_fullDay180,Manual_fullDay250,Manual_fullDay70_180,Manual_fullDay70_150,Manual_fullDay70,Manual_fullDay54,1.1], [Auto_overnight_180,Auto_overnight_250,Auto_overnight_70_180,Auto_overnight_70_150,Auto_overnight_70,Auto_overnight_54,Auto_daytime180,Auto_daytime250,Auto_daytime70_180,Auto_daytime70_150,Auto_daytime70,Auto_daytime54,Auto_fullDay180,Auto_fullDay250,Auto_fullDay70_180,Auto_fullDay70_150,Auto_fullDay70,Auto_fullDay54,1.1]]

Results = pd.DataFrame(data)
Results.to_csv('/content/Results.csv', header=False, index=False)

"""# New Section"""





"""# New Section"""